config/routes.rb
Rails.application.routes.draw do
  
 #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
 root 'static_pages#top'
 
 resources :users do
 end
 
 resources :halls do
   member do
     get 'change_map'
   end
 end
 
 resources :kitchens do
    end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <h1><%= link_to "Task App", root_path %></h1>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "従業員一覧", users_path %></li>
          <li><%= link_to  "スキルマップ", user_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             プロフィール <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "編集", '#' %></li>
              <li><%= link_to "タスク一覧", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path %>
              </li>
              <% else %>
                <%= link_to "新規作成",  new_user_registration_path %>
                <%= link_to "ログイン", new_user_session_path %>
              <% end %>
            </ul>
          </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkillMapApp</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <header>
      <%= render '/layouts/header' %>
    </header>
    <%= yield %>
  </body>
</html>